// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReservation.Db;

#nullable disable

namespace RestaurantReservation.Db.Migrations
{
    [DbContext(typeof(RestaurantReservationDbContext))]
    [Migration("20250916165506_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantReservation.Db.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", "Restaurant");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Email = "alice@email.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "555-1234"
                        },
                        new
                        {
                            CustomerID = 2,
                            Email = "bob@email.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            PhoneNumber = "555-2345"
                        },
                        new
                        {
                            CustomerID = 3,
                            Email = "charlie@email.com",
                            FirstName = "Charlie",
                            LastName = "Davis",
                            PhoneNumber = "555-3456"
                        },
                        new
                        {
                            CustomerID = 4,
                            Email = "diana@email.com",
                            FirstName = "Diana",
                            LastName = "Evans",
                            PhoneNumber = "555-4567"
                        },
                        new
                        {
                            CustomerID = 5,
                            Email = "ethan@email.com",
                            FirstName = "Ethan",
                            LastName = "Brown",
                            PhoneNumber = "555-5678"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Employee", "Restaurant");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            FirstName = "John",
                            LastName = "Manager",
                            Position = "Manager",
                            RestaurantID = 1
                        },
                        new
                        {
                            EmployeeID = 2,
                            FirstName = "Sara",
                            LastName = "Manager",
                            Position = "Manager",
                            RestaurantID = 2
                        },
                        new
                        {
                            EmployeeID = 3,
                            FirstName = "Mike",
                            LastName = "Chef",
                            Position = "Chef",
                            RestaurantID = 3
                        },
                        new
                        {
                            EmployeeID = 4,
                            FirstName = "Lucy",
                            LastName = "Waiter",
                            Position = "Waiter",
                            RestaurantID = 4
                        },
                        new
                        {
                            EmployeeID = 5,
                            FirstName = "Tom",
                            LastName = "Waiter",
                            Position = "Waiter",
                            RestaurantID = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("MenuItem", "Restaurant");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Description = "Delicious cheeseburger",
                            Name = "Cheeseburger",
                            Price = 9.99m,
                            RestaurantID = 1
                        },
                        new
                        {
                            ItemID = 2,
                            Description = "Tasty pizza",
                            Name = "Pepperoni Pizza",
                            Price = 12.50m,
                            RestaurantID = 2
                        },
                        new
                        {
                            ItemID = 3,
                            Description = "Classic pasta",
                            Name = "Spaghetti",
                            Price = 11.00m,
                            RestaurantID = 3
                        },
                        new
                        {
                            ItemID = 4,
                            Description = "Fresh salad",
                            Name = "Caesar Salad",
                            Price = 8.25m,
                            RestaurantID = 4
                        },
                        new
                        {
                            ItemID = 5,
                            Description = "Juicy salmon",
                            Name = "Grilled Salmon",
                            Price = 15.50m,
                            RestaurantID = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Order", "Restaurant");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            EmployeeID = 1,
                            OrderDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationID = 1,
                            TotalAmount = 19.98m
                        },
                        new
                        {
                            OrderID = 2,
                            EmployeeID = 2,
                            OrderDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationID = 2,
                            TotalAmount = 25.00m
                        },
                        new
                        {
                            OrderID = 3,
                            EmployeeID = 3,
                            OrderDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationID = 3,
                            TotalAmount = 33.00m
                        },
                        new
                        {
                            OrderID = 4,
                            EmployeeID = 4,
                            OrderDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationID = 4,
                            TotalAmount = 24.75m
                        },
                        new
                        {
                            OrderID = 5,
                            EmployeeID = 5,
                            OrderDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationID = 5,
                            TotalAmount = 15.50m
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem", "Restaurant");

                    b.HasData(
                        new
                        {
                            OrderItemID = 1,
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemID = 2,
                            ItemID = 2,
                            OrderID = 2,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemID = 3,
                            ItemID = 3,
                            OrderID = 3,
                            Quantity = 3
                        },
                        new
                        {
                            OrderItemID = 4,
                            ItemID = 4,
                            OrderID = 4,
                            Quantity = 3
                        },
                        new
                        {
                            OrderItemID = 5,
                            ItemID = 5,
                            OrderID = 5,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("TableID");

                    b.ToTable("Reservation", "Restaurant");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerID = 1,
                            PartySize = 2,
                            ReservationDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantID = 1,
                            TableID = 1
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerID = 2,
                            PartySize = 2,
                            ReservationDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantID = 2,
                            TableID = 3
                        },
                        new
                        {
                            ReservationID = 3,
                            CustomerID = 3,
                            PartySize = 4,
                            ReservationDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantID = 3,
                            TableID = 4
                        },
                        new
                        {
                            ReservationID = 4,
                            CustomerID = 4,
                            PartySize = 3,
                            ReservationDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantID = 4,
                            TableID = 5
                        },
                        new
                        {
                            ReservationID = 5,
                            CustomerID = 5,
                            PartySize = 2,
                            ReservationDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantID = 5,
                            TableID = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RestaurantID");

                    b.ToTable("Restaurant", "Restaurant");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            Address = "123 Main St",
                            Name = "Downtown Diner",
                            OpeningHours = "9:00 AM - 10:00 PM",
                            PhoneNumber = "555-1234"
                        },
                        new
                        {
                            RestaurantID = 2,
                            Address = "456 Elm St",
                            Name = "Pizza Palace",
                            OpeningHours = "11:00 AM - 11:00 PM",
                            PhoneNumber = "555-1235"
                        },
                        new
                        {
                            RestaurantID = 3,
                            Address = "789 Oak St",
                            Name = "Pasta Corner",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            PhoneNumber = "555-1236"
                        },
                        new
                        {
                            RestaurantID = 4,
                            Address = "321 Pine St",
                            Name = "Salad Stop",
                            OpeningHours = "8:00 AM - 8:00 PM",
                            PhoneNumber = "555-1237"
                        },
                        new
                        {
                            RestaurantID = 5,
                            Address = "654 Maple Ave",
                            Name = "Seafood Shack",
                            OpeningHours = "12:00 PM - 12:00 AM",
                            PhoneNumber = "555-1238"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("TableID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Table", "Restaurant");

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            Capacity = 2,
                            RestaurantID = 1
                        },
                        new
                        {
                            TableID = 2,
                            Capacity = 4,
                            RestaurantID = 1
                        },
                        new
                        {
                            TableID = 3,
                            Capacity = 2,
                            RestaurantID = 2
                        },
                        new
                        {
                            TableID = 4,
                            Capacity = 4,
                            RestaurantID = 3
                        },
                        new
                        {
                            TableID = 5,
                            Capacity = 3,
                            RestaurantID = 4
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Reservation", "Reservation")
                        .WithMany("Orders")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.Db.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.HasOne("RestaurantReservation.Db.Models.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Reservation", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Restaurant", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("MenuItems");

                    b.Navigation("Reservations");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantReservation.Db.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
